### ISSUE TITLE
use wordlist-4096 for denser encoding

### ISSUE THREAD

**Issue by kklash** [kklash/mnemonikey#25]
Transferring this over from https://github.com/kklash/mnemonikey/discussions/21

I created [a 4096-length wordlist](https://github.com/kklash/wordlist-4096) which will give us denser 12-bits-per-word encoding. This should help fit more data into fewer words. Hopefully we can use that to add passphrase-encrypted recovery phrases: https://github.com/kklash/mnemonikey/discussions/16

**Comment by RyanZim** [comment]
@kklash Your wordlist repo is apparently a private repo, FYI.

**Comment by kklash** [comment]
woops! fixed
