### ISSUE TITLE
automated CI builds

### ISSUE THREAD

**Issue by kklash** [kklash/mnemonikey#31]
We should add CI to automatically build Linux and MacOS binaries for Git tags.

**Comment by anurag-rajawat** [comment]
Hi @kklash!
Do we only need to build the binary or release it as well?

**Comment by anurag-rajawat** [comment]
We'll set up one pipeline to automate builds and another for releases so users can download binaries as per their systems. 
Are you okay with this?

**Comment by kklash** [comment]
That sounds great! Thanks

-------- Original Message --------

**Comment by kklash** [comment]
> And do we need to build for Windows as well?

I personally don't have a windows machine to test on. I think we can leave windows out for now, unless it's very easy to add in which case, why not!
